### ISSUE TITLE
CSS bestanden staan op verschillende plaatsen

### ISSUE THREAD

**Issue by reithose** [geensnor/geensnor.nl-oud#19]
Dat is niet zo handig. In de CSS map en in de Assets map.

**Comment by Zuijdam** [comment]
Ja! Viel mij iok op

Erik

**Comment by reithose** [comment]
Ja, dat is met jouw lightbox dinges ontstaan.

**Comment by Zuijdam** [comment]
Weet ik

Erik

**Comment by Zuijdam** [comment]
fixed
https://github.com/geensnor/geensnor.nl/commit/1064282343aa43f0efdfa6b5d484f2134ee29840
