### ISSUE TITLE
Afbeeldingen converteren

### ISSUE THREAD

**Issue by reithose** [geensnor/geensnor.nl-oud#30]
Tijdens het builden de afbeeldingen converteren naar avif en ze een goed formaat meegeven: https://bortox.it/en/article/jekyll-blog-webp-avif-images/. Is ook de belangrijkste tip van Google: https://pagespeed.web.dev/report?url=https%3A%2F%2Fgeensnor.nl%2F

**Comment by reithose** [comment]
Leuk idee maar ik ben totaal afgehaakt na dit zinnetje:

> Deploying a site with JPT is surprisingly tricky.

**Comment by Zuijdam** [comment]
Zullen we hem danmaar closen?

**Comment by reithose** [comment]
Ja, misschien is dat het beste. Op www.omloopdesnor.nl gebeurt dit inmiddels wel allemaal super mooi. Maar in Jekyll blijkt het toch wat lastiger te zijn.
