### ISSUE TITLE
security.txt doet het niet

### ISSUE THREAD

**Issue by Zuijdam** [geensnor/geensnor.nl-oud#40]
https://geensnor.nl/.well-known/security.txt

geeft om nog onduidelijke reden een 404

**Comment by reithose** [comment]
Ik denk dat het iets te maken heeft met de migratie van de ene naar de andere hoster en dat ik de hele .well-known directory ben vergeten.

**Comment by Zuijdam** [comment]
Hij staat wel op netlify. Denk dat het daar mee te maken heeft. Er staat niks op geensnorOp 30 mei 2023 om 22:11 heeft Joris ***@***.***> het volgende geschreven:﻿
Ik denk dat het iets te maken heeft met de migratie van de ene naar de andere hoster en dat ik de hele .well-known directory ben vergeten.

**Comment by reithose** [comment]
aahja, dat kan ook.

**Comment by reithose** [comment]
ennu?

**Comment by Zuijdam** [comment]
Janken denk ik...in een hoekje.

**Comment by Zuijdam** [comment]
ik sluit hem maar
