### ISSUE TITLE
post detail page mist afbeelding

### ISSUE THREAD

**Issue by Zuijdam** [geensnor/geensnor.nl-oud#5]
op de detail pagina van een post wordt de afbeelding niet gerendert (geeft een 404). Op het overzicht gaat het wel goed

niet goed:
https://geensnor.netlify.app/2020/10/06/Schwung-Screen.html 

wel goed:
www.geensnor.nl

**Comment by reithose** [comment]
Ja, na lang onderzoek is het lek boven. Er miste een / in je post. Met deze commit hebben we deze tragedie een halt toe kunnen roepen: https://github.com/geensnor/geensnor.nl/commit/51f2fb67ac1b501bad9a9fb877eb883f33da309d

**Comment by Zuijdam** [comment]
Ochja natuurlijk. Hij kijkt vanaf de huidige positie dus moet eerst terug naar de root
