### ISSUE TITLE
Twitter post is stuk

### ISSUE THREAD

**Issue by Zuijdam** [geensnor/geensnor.nl-oud#6]
Automatische twitterpost heeft geen url
![image](https://user-images.githubusercontent.com/35580176/95369614-f1a44e80-08d7-11eb-9ff9-e56c021617ac.jpeg)

**Comment by reithose** [comment]
Er was geen url geconfigureerd in de _config.yml. Nu wel. Denk dat IFTTT dat stuk er wel graag voor wil hebben.

**Comment by reithose** [comment]
Kijk. Het werkt weer als een trein: https://twitter.com/geensnor/status/1314843203770646529
